# Write a program to input eight numbers from the user and display all the unique numbers
s =set()
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)
n = int(input("enter the numbers:"))
s.add(n)

print(s)